#!/bin/bash
set -eEu
set -o pipefail

################################################################################
# Run `ci/test' to run the test harness.
################################################################################

# Ensure dependencies are up-to-date.
. ci/bootstrap

# Run various checks unrelated to Puppet.
run_precommit

# Syntax check Hiera config files.
/usr/bin/time rake syntax:hiera

# Syntax check Puppet manifests.
/usr/bin/time rake syntax:manifests

# Syntax check Puppet templates.
/usr/bin/time rake syntax:templates

# In-module hiera data depends on having a correct metadata.json file.
# It is strongly recommended to use metadata-json-lint to
# automatically check metadata.json file before running rspec.
echo '---> metadata_lint'
/usr/bin/time rake metadata_lint

# Check ruby code, including rspec, for style.
echo '---> rubocop'
/usr/bin/time rake rubocop

# Run spec tests.
echo '---> spec'
/usr/bin/time rake spec
